// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx-WJZxA08S04Cx1EzIyHtuoCagOP-tw4',
    appId: '1:814252788949:web:a1536d180dddd0bbc2265c',
    messagingSenderId: '814252788949',
    projectId: 'uts-marketplace',
    authDomain: 'uts-marketplace.firebaseapp.com',
    storageBucket: 'uts-marketplace.firebasestorage.app',
    measurementId: 'G-X496W05PJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxtr2MJ-9ugV_Gv1jQd7qIUT5yFdhQOio',
    appId: '1:814252788949:android:e587b1d5a6980b78c2265c',
    messagingSenderId: '814252788949',
    projectId: 'uts-marketplace',
    storageBucket: 'uts-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71l7b8RsONZrbWMkXLwQ1FcQVErX154I',
    appId: '1:814252788949:ios:7cfe9cc4fdc5f806c2265c',
    messagingSenderId: '814252788949',
    projectId: 'uts-marketplace',
    storageBucket: 'uts-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.marketplacePapua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC71l7b8RsONZrbWMkXLwQ1FcQVErX154I',
    appId: '1:814252788949:ios:7cfe9cc4fdc5f806c2265c',
    messagingSenderId: '814252788949',
    projectId: 'uts-marketplace',
    storageBucket: 'uts-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.marketplacePapua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx-WJZxA08S04Cx1EzIyHtuoCagOP-tw4',
    appId: '1:814252788949:web:8c47499bb523511bc2265c',
    messagingSenderId: '814252788949',
    projectId: 'uts-marketplace',
    authDomain: 'uts-marketplace.firebaseapp.com',
    storageBucket: 'uts-marketplace.firebasestorage.app',
    measurementId: 'G-6YC7R1YVNK',
  );

}